name: Duplicate Issue

on:
  issue_comment:
    types: [created, edited]

jobs:
  check_duplicate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Check issue title
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        if: github.event.comment.body == '/duplicate'
        script: |
          const sourceIssue = context.payload.issue;
          const labels = sourceIssue.labels.map(label => label.name);
          const assignees = sourceIssue.assignees.map(assignee => assignee.login);
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `${sourceIssue.title} Copy`,
            body: sourceIssue.body,
            labels: labels,
            assignees: assignees,
          })