name: Issue Title Check

on:
  issues:
    types: [opened]

jobs:
  check_title:
    runs-on: ubuntu-latest
    steps:
    - name: Check issue title
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const title = context.payload.issue.title;
          console.log(`Issue title: ${title}`);
          if (!title.startsWith("[CI/CD]") && !title.startsWith("[iOS]")) {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Issueタイトルには[CI/CD]または[iOS]のプレフィックスが必要です。"
            });
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "closed"
            });
          }
